name: QA

on:
- workflow_dispatch
- push
- pull_request

jobs:
  quality-assurance:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6
      - uses: php-actions/phpstan@v3
        with:
          configuration: phpstan.neon
          php_version: 8.2

      - name: Analyze code quality assurance
        run: make analyze
